@extends('layouts.app')

@section('content')
<div class="grid grid-cols-1 lg:grid-cols-3 gap-6">
    <!-- Form Section -->
    <div class="lg:col-span-2">
        <div class="bg-white rounded-lg shadow-lg overflow-hidden">
            <!-- Header with Gradient -->
            <div class="bg-gradient-to-r from-amber-500 to-amber-600 px-8 py-6 flex items-center gap-4">
                <div class="w-14 h-14 bg-white bg-opacity-20 rounded-lg flex items-center justify-center">
                    <i class="fas fa-plus text-white text-2xl"></i>
                </div>
                <div>
                    <h1 class="text-2xl font-bold text-white">Tambah Supplier Baru</h1>
                    <p class="text-amber-100 text-sm mt-1">Isi form di bawah untuk menambahkan supplier baru</p>
                </div>
            </div>

            <!-- Form Content -->
            <form action="{{ route('supplier.store') }}" method="POST" class="p-8" id="formSupplier">
                @csrf

                <div class="space-y-6">
                    <!-- Kode Supplier -->
                    <div>
                        <label class="block text-sm font-semibold text-gray-700 mb-2">
                            <i class="fas fa-barcode text-amber-500 mr-2"></i>Kode Supplier
                        </label>
                        <input type="text" readonly 
                            placeholder="Auto Generated By System"
                            class="w-full px-4 py-3 bg-gray-100 border-2 border-gray-200 rounded-lg text-gray-600 font-semibold">
                        <p class="text-xs text-gray-500 mt-1">Kode akan dihasilkan otomatis oleh sistem</p>
                    </div>

                    <!-- Nama Supplier -->
                    <div>
                        <label class="block text-sm font-semibold text-gray-700 mb-2">
                            <i class="fas fa-store text-amber-500 mr-2"></i>Nama Supplier <span class="text-red-500">*</span>
                        </label>
                        <input type="text" name="nama_supplier" required 
                            placeholder="Contoh: PT. Sumber Makmur"
                            class="w-full px-4 py-3 border-2 border-gray-200 rounded-lg focus:outline-none focus:border-amber-500 focus:ring-2 focus:ring-amber-200 transition-all @error('nama_supplier') border-red-500 @enderror">
                        @error('nama_supplier')
                            <p class="text-xs text-red-500 mt-1"><i class="fas fa-exclamation-circle mr-1"></i>{{ $message }}</p>
                        @enderror
                    </div>

                    <!-- Telepon -->
                    <div>
                        <label class="block text-sm font-semibold text-gray-700 mb-2">
                            <i class="fas fa-phone text-amber-500 mr-2"></i>Telepon
                        </label>
                        <input type="text" name="telepon" 
                            placeholder="Contoh: 08123456789"
                            class="w-full px-4 py-3 border-2 border-gray-200 rounded-lg focus:outline-none focus:border-amber-500 focus:ring-2 focus:ring-amber-200 transition-all @error('telepon') border-red-500 @enderror">
                        @error('telepon')
                            <p class="text-xs text-red-500 mt-1"><i class="fas fa-exclamation-circle mr-1"></i>{{ $message }}</p>
                        @enderror
                    </div>

                    <!-- Alamat -->
                    <div>
                        <label class="block text-sm font-semibold text-gray-700 mb-2">
                            <i class="fas fa-map-marker-alt text-amber-500 mr-2"></i>Alamat
                        </label>
                        <textarea name="alamat" rows="3"
                            placeholder="Masukkan alamat lengkap supplier"
                            class="w-full px-4 py-3 border-2 border-gray-200 rounded-lg focus:outline-none focus:border-amber-500 focus:ring-2 focus:ring-amber-200 transition-all resize-none @error('alamat') border-red-500 @enderror"></textarea>
                        @error('alamat')
                            <p class="text-xs text-red-500 mt-1"><i class="fas fa-exclamation-circle mr-1"></i>{{ $message }}</p>
                        @enderror
                    </div>

                    <!-- Status -->
                    <div>
                        <label class="block text-sm font-semibold text-gray-700 mb-2">
                            <i class="fas fa-toggle-on text-amber-500 mr-2"></i>Status <span class="text-red-500">*</span>
                        </label>
                        <select name="status" required 
                            class="w-full px-4 py-3 border-2 border-gray-200 rounded-lg focus:outline-none focus:border-amber-500 focus:ring-2 focus:ring-amber-200 transition-all @error('status') border-red-500 @enderror">
                            <option value="">Pilih Status</option>
                            <option value="Aktif">Aktif</option>
                            <option value="Nonaktif">Nonaktif</option>
                        </select>
                        @error('status')
                            <p class="text-xs text-red-500 mt-1"><i class="fas fa-exclamation-circle mr-1"></i>{{ $message }}</p>
                        @enderror
                    </div>

                    <!-- Catatan -->
                    <div>
                        <label class="block text-sm font-semibold text-gray-700 mb-2">
                            <i class="fas fa-sticky-note text-amber-500 mr-2"></i>Catatan
                        </label>
                        <textarea name="catatan" rows="3"
                            placeholder="Tambahkan catatan khusus untuk supplier ini (opsional)"
                            class="w-full px-4 py-3 border-2 border-gray-200 rounded-lg focus:outline-none focus:border-amber-500 focus:ring-2 focus:ring-amber-200 transition-all resize-none @error('catatan') border-red-500 @enderror"></textarea>
                        @error('catatan')
                            <p class="text-xs text-red-500 mt-1"><i class="fas fa-exclamation-circle mr-1"></i>{{ $message }}</p>
                        @enderror
                    </div>
                </div>

                <!-- Buttons -->
                <div class="flex gap-3 mt-8 pt-6 border-t-2 border-gray-200">
                    <a href="{{ route('supplier.index') }}" class="flex-1 px-4 py-3 bg-gray-200 hover:bg-gray-300 text-gray-700 font-semibold rounded-lg transition-all duration-200 text-center">
                        <i class="fas fa-arrow-left mr-2"></i>Kembali
                    </a>
                    <button type="button" id="btnSubmit" class="flex-1 px-4 py-3 bg-gradient-to-r from-amber-500 to-amber-600 hover:from-amber-600 hover:to-amber-700 text-white font-semibold rounded-lg transition-all duration-200 shadow-lg hover:shadow-xl">
                        <i class="fas fa-save mr-2"></i>Simpan Supplier
                    </button>
                </div>
            </form>
        </div>
    </div>

    <!-- Sidebar Tips -->
    <div class="lg:col-span-1">
        <div class="bg-white rounded-lg shadow-lg p-6 sticky top-6">
            <h3 class="text-lg font-bold text-gray-900 mb-4 flex items-center gap-2">
                <i class="fas fa-lightbulb text-amber-500"></i>Tips Berguna
            </h3>
            <div class="space-y-4">
                <div class="bg-blue-50 border-l-4 border-blue-500 p-3 rounded">
                    <p class="text-sm font-semibold text-blue-700 mb-1"><i class="fas fa-info-circle mr-1"></i>Info Penting</p>
                    <p class="text-xs text-blue-600">Nama supplier harus unik dan mudah diingat untuk identifikasi yang lebih baik</p>
                </div>
                <div class="bg-green-50 border-l-4 border-green-500 p-3 rounded">
                    <p class="text-sm font-semibold text-green-700 mb-1"><i class="fas fa-phone mr-1"></i>Kontak</p>
                    <p class="text-xs text-green-600">Pastikan nomor telepon supplier valid untuk komunikasi yang efektif</p>
                </div>
                <div class="bg-amber-50 border-l-4 border-amber-500 p-3 rounded">
                    <p class="text-sm font-semibold text-amber-700 mb-1"><i class="fas fa-map mr-1"></i>Lokasi</p>
                    <p class="text-xs text-amber-600">Alamat lengkap diperlukan untuk pengiriman dan dokumentasi</p>
                </div>
                <div class="bg-purple-50 border-l-4 border-purple-500 p-3 rounded">
                    <p class="text-sm font-semibold text-purple-700 mb-1"><i class="fas fa-check mr-1"></i>Status</p>
                    <p class="text-xs text-purple-600">Pilih "Aktif" jika supplier siap melakukan transaksi</p>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@push('scripts')
<script>
document.getElementById('btnSubmit').addEventListener('click', function() {
    Swal.fire({
        title: 'Simpan Data Supplier?',
        text: 'Pastikan semua data sudah benar sebelum menyimpan',
        icon: 'question',
        showCancelButton: true,
        confirmButtonColor: '#f59e0b',
        cancelButtonColor: '#d1d5db',
        confirmButtonText: 'Ya, Simpan',
        cancelButtonText: 'Batal',
        customClass: {
            confirmButton: 'px-6 py-2 rounded-lg font-semibold transition-all duration-200',
            cancelButton: 'px-6 py-2 rounded-lg font-semibold transition-all duration-200'
        }
    }).then((result) => {
        if (result.isConfirmed) {
            document.getElementById('formSupplier').submit();
        }
    });
});
</script>
@endpush
